include $(THEOS)/makefiles/common.mk

TOOL_NAME = rsfonts

$(TOOL_NAME)_FILES = rsfonts.m
$(TOOL_NAME)_CFLAGS = -fobjc-arc
$(TOOL_NAME)_CODESIGN_FLAGS = -S../entitlements-apfs.xml

include $(THEOS_MAKE_PATH)/tool.mk
